# Generated by Django 2.1.1 on 2018-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20180924_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_email',
            field=models.EmailField(max_length=200),
        ),
    ]
