# Generated by Django 2.1.1 on 2018-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20180924_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice1',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choice3',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
