# Generated by Django 2.1.1 on 2018-09-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_auto_20180926_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice1',
        ),
    ]
