# Generated by Django 2.1.1 on 2018-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_remove_choice_choice1'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice1',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
